package org.metamechanists.metacoin.core;

import me.justahuman.furnished.displaymodellib.models.ModelBuilder;
import me.justahuman.furnished.displaymodellib.models.components.ModelCuboid;
import me.justahuman.furnished.displaymodellib.models.components.ModelDiamond;
import me.justahuman.furnished.displaymodellib.models.components.ModelItem;
import org.bukkit.Material;
import org.bukkit.entity.Display;

import static org.metamechanists.metacoin.core.ItemStacks.META_COIN;

public class Models {
    public static ModelBuilder META_COIN_MINER() {
        return new ModelBuilder()
                .add("base", new ModelCuboid()
                        .brightness(15)
                        .material(Material.GLASS)
                        .size(1.2F)
                        .location(0, 0, 0))

                .add("base-pillar-1", new ModelCuboid()
                        .brightness(15)
                        .material(Material.WHITE_CONCRETE)
                        .size(0.35F, 2.0F, 0.35F)
                        .location(1.5F, 0.5F, 0.0F)
                        .rotation(0))
                .add("base-pillar-2", new ModelCuboid()
                        .brightness(15)
                        .material(Material.WHITE_CONCRETE)
                        .size(0.35F, 2.0F, 0.35F)
                        .location(1.06F, 0.5F, 1.06F)
                        .rotation(Math.PI / 4))
                .add("base-pillar-3", new ModelCuboid()
                        .brightness(15)
                        .material(Material.WHITE_CONCRETE)
                        .size(0.35F, 2.0F, 0.35F)
                        .location(0.0F, 0.5F, 1.5F)
                        .rotation(0))
                .add("base-pillar-4", new ModelCuboid()
                        .brightness(15)
                        .material(Material.WHITE_CONCRETE)
                        .size(0.35F, 2.0F, 0.35F)
                        .location(-1.06F, 0.5F, 1.06F)
                        .rotation(Math.PI / 4))
                .add("base-pillar-5", new ModelCuboid()
                        .brightness(15)
                        .material(Material.WHITE_CONCRETE)
                        .size(0.35F, 2.0F, 0.35F)
                        .location(-1.5F, 0.5F, 0.0F)
                        .rotation(0))
                .add("base-pillar-6", new ModelCuboid()
                        .brightness(15)
                        .material(Material.WHITE_CONCRETE)
                        .size(0.35F, 2.0F, 0.35F)
                        .location(1.06F, 0.5F, -1.06F)
                        .rotation(Math.PI / 4))
                .add("base-pillar-7", new ModelCuboid()
                        .brightness(15)
                        .material(Material.WHITE_CONCRETE)
                        .size(0.35F, 2.0F, 0.35F)
                        .location(0.0F, 0.5F, -1.5F)
                        .rotation(0))
                .add("base-pillar-8", new ModelCuboid()
                        .brightness(15)
                        .material(Material.WHITE_CONCRETE)
                        .size(0.35F, 2.0F, 0.35F)
                        .location(-1.06F, 0.5F, -1.06F)
                        .rotation(Math.PI / 4))

                .add("bottom-plate-1", new ModelCuboid()
                        .brightness(15)
                        .material(Material.WHITE_CONCRETE)
                        .size(3.4F, 1.0F, 1.4F)
                        .location(0, 2.0F, 0)
                        .rotation(0))
                .add("bottom-plate-2", new ModelCuboid()
                        .brightness(15)
                        .material(Material.WHITE_CONCRETE)
                        .size(3.4F, 1.0F, 1.34F)
                        .location(0, 2.0F, 0)
                        .rotation(Math.PI / 4))
                .add("bottom-plate-3", new ModelCuboid()
                        .brightness(15)
                        .material(Material.WHITE_CONCRETE)
                        .size(3.4F, 1.0F, 1.4F)
                        .location(0, 2.0F, 0)
                        .rotation(Math.PI / 2))
                .add("bottom-plate-4", new ModelCuboid()
                        .brightness(15)
                        .material(Material.WHITE_CONCRETE)
                        .size(3.4F, 1.0F, 1.4F)
                        .location(0, 2.0F, 0)
                        .rotation(Math.PI * 3 / 4))

                .add("bottom-plate-outside-1", new ModelCuboid()
                        .brightness(15)
                        .material(Material.BLUE_CONCRETE)
                        .size(3.5F, 0.7F, 1.1F)
                        .location(0, 2.0F, 0)
                        .rotation(0))
                .add("bottom-plate-outside-2", new ModelCuboid()
                        .brightness(15)
                        .material(Material.BLUE_CONCRETE)
                        .size(3.5F, 0.7F, 1.1F)
                        .location(0, 2.0F, 0)
                        .rotation(Math.PI / 4))
                .add("bottom-plate-outside-3", new ModelCuboid()
                        .brightness(15)
                        .material(Material.BLUE_CONCRETE)
                        .size(3.5F, 0.7F, 1.1F)
                        .location(0, 2.0F, 0)
                        .rotation(Math.PI / 2))
                .add("bottom-plate-outside-4", new ModelCuboid()
                        .brightness(15)
                        .material(Material.BLUE_CONCRETE)
                        .size(3.5F, 0.7F, 1.1F)
                        .location(0, 2.0F, 0)
                        .rotation(Math.PI * 3 / 4))

                .add("bottom-slanted-pillar-1", new ModelCuboid()
                        .brightness(15)
                        .material(Material.WHITE_CONCRETE)
                        .size(0.35F, 2.5F, 0.35F)
                        .location(0.9F, 3.5F, 0.0F)
                        .rotation(0, 0, Math.PI * 1 / 6))
                .add("bottom-slanted-pillar-2", new ModelCuboid()
                        .brightness(15)
                        .material(Material.WHITE_CONCRETE)
                        .size(0.35F, 2.5F, 0.35F)
                        .location(0.64F, 3.5F, -0.64F)
                        .rotation(0, Math.PI / 4, Math.PI * 1 / 6))
                .add("bottom-slanted-pillar-3", new ModelCuboid()
                        .brightness(15)
                        .material(Material.WHITE_CONCRETE)
                        .size(0.35F, 2.5F, 0.35F)
                        .location(0.0F, 3.5F, -0.9F)
                        .rotation(0, Math.PI / 2, Math.PI * 1 / 6))
                .add("bottom-slanted-pillar-4", new ModelCuboid()
                        .brightness(15)
                        .material(Material.WHITE_CONCRETE)
                        .size(0.35F, 2.5F, 0.35F)
                        .location(-0.64F, 3.5F, -0.64F)
                        .rotation(0, Math.PI * 3 / 4, Math.PI * 1 / 6))
                .add("bottom-slanted-pillar-5", new ModelCuboid()
                        .brightness(15)
                        .material(Material.WHITE_CONCRETE)
                        .size(0.35F, 2.5F, 0.35F)
                        .location(-0.9F, 3.5F, 0.0F)
                        .rotation(0, Math.PI, Math.PI * 1 / 6))
                .add("bottom-slanted-pillar-6", new ModelCuboid()
                        .brightness(15)
                        .material(Material.WHITE_CONCRETE)
                        .size(0.35F, 2.5F, 0.35F)
                        .location(-0.64F, 3.5F, 0.64F)
                        .rotation(0, Math.PI * 5 / 4, Math.PI * 1 / 6))
                .add("bottom-slanted-pillar-7", new ModelCuboid()
                        .brightness(15)
                        .material(Material.WHITE_CONCRETE)
                        .size(0.35F, 2.5F, 0.35F)
                        .location(0, 3.5F, 0.9F)
                        .rotation(0, Math.PI * 3 / 2, Math.PI * 1 / 6))
                .add("bottom-slanted-pillar-8", new ModelCuboid()
                        .brightness(15)
                        .material(Material.WHITE_CONCRETE)
                        .size(0.35F, 2.5F, 0.35F)
                        .location(0.64F, 3.5F, 0.64F)
                        .rotation(0, Math.PI * 7/ 4, Math.PI * 1 / 6))

                .add("bottom-shroomlight", new ModelDiamond()
                        .brightness(15)
                        .material(Material.SHROOMLIGHT)
                        .size(2.0F)
                        .location(0.0F, 2.0F, 0.0F))

                .add("bottom-laser", new ModelCuboid()
                        .brightness(15)
                        .material(Material.RED_CONCRETE)
                        .size(0.1F, 2.5F, 0.1F)
                        .location(0, 4.0F, 0))

                .add("metacoin", new ModelItem()
                        .brightness(15)
                        .item(META_COIN)
                        .billboard(Display.Billboard.VERTICAL)
                        .size(2.0F)
                        .location(0, 6.0F, 0))

                .add("top-laser", new ModelCuboid()
                        .brightness(15)
                        .material(Material.RED_CONCRETE)
                        .size(0.1F, 2.5F, 0.1F)
                        .location(0, 8.0F, 0))

                .add("top-shroomlight", new ModelDiamond()
                        .brightness(15)
                        .material(Material.SHROOMLIGHT)
                        .size(2.0F)
                        .location(0.0F, 10.0F, 0.0F))

                .add("top-slanted-pillar-1", new ModelCuboid()
                        .brightness(15)
                        .material(Material.WHITE_CONCRETE)
                        .size(0.35F, 2.5F, 0.35F)
                        .location(0.9F, 8.5F, 0.0F)
                        .rotation(0, 0, -Math.PI * 1 / 6))
                .add("top-slanted-pillar-2", new ModelCuboid()
                        .brightness(15)
                        .material(Material.WHITE_CONCRETE)
                        .size(0.35F, 2.5F, 0.35F)
                        .location(0.64F, 8.5F, -0.64F)
                        .rotation(0, Math.PI / 4, -Math.PI * 1 / 6))
                .add("top-slanted-pillar-3", new ModelCuboid()
                        .brightness(15)
                        .material(Material.WHITE_CONCRETE)
                        .size(0.35F, 2.5F, 0.35F)
                        .location(0.0F, 8.5F, -0.9F)
                        .rotation(0, Math.PI / 2, -Math.PI * 1 / 6))
                .add("top-slanted-pillar-4", new ModelCuboid()
                        .brightness(15)
                        .material(Material.WHITE_CONCRETE)
                        .size(0.35F, 2.5F, 0.35F)
                        .location(-0.64F, 8.5F, -0.64F)
                        .rotation(0, Math.PI * 3 / 4, -Math.PI * 1 / 6))
                .add("top-slanted-pillar-5", new ModelCuboid()
                        .brightness(15)
                        .material(Material.WHITE_CONCRETE)
                        .size(0.35F, 2.5F, 0.35F)
                        .location(-0.9F, 8.5F, 0.0F)
                        .rotation(0, Math.PI, -Math.PI * 1 / 6))
                .add("top-slanted-pillar-6", new ModelCuboid()
                        .brightness(15)
                        .material(Material.WHITE_CONCRETE)
                        .size(0.35F, 2.5F, 0.35F)
                        .location(-0.64F, 8.5F, 0.64F)
                        .rotation(0, Math.PI * 5 / 4, -Math.PI * 1 / 6))
                .add("top-slanted-pillar-7", new ModelCuboid()
                        .brightness(15)
                        .material(Material.WHITE_CONCRETE)
                        .size(0.35F, 2.5F, 0.35F)
                        .location(0, 8.5F, 0.9F)
                        .rotation(0, Math.PI * 3 / 2, -Math.PI * 1 / 6))
                .add("top-slanted-pillar-8", new ModelCuboid()
                        .brightness(15)
                        .material(Material.WHITE_CONCRETE)
                        .size(0.35F, 2.5F, 0.35F)
                        .location(0.64F, 8.5F, 0.64F)
                        .rotation(0, Math.PI * 7/ 4, -Math.PI * 1 / 6))

                .add("top-plate-1", new ModelCuboid()
                        .brightness(15)
                        .material(Material.WHITE_CONCRETE)
                        .size(3.4F, 1.0F, 1.4F)
                        .location(0, 10.0F, 0)
                        .rotation(0))
                .add("top-plate-2", new ModelCuboid()
                        .brightness(15)
                        .material(Material.WHITE_CONCRETE)
                        .size(3.4F, 1.0F, 1.34F)
                        .location(0, 10.0F, 0)
                        .rotation(Math.PI / 4))
                .add("top-plate-3", new ModelCuboid()
                        .brightness(15)
                        .material(Material.WHITE_CONCRETE)
                        .size(3.4F, 1.0F, 1.4F)
                        .location(0, 10.0F, 0)
                        .rotation(Math.PI / 2))
                .add("top-plate-4", new ModelCuboid()
                        .brightness(15)
                        .material(Material.WHITE_CONCRETE)
                        .size(3.4F, 1.0F, 1.4F)
                        .location(0, 10.0F, 0)
                        .rotation(Math.PI * 3 / 4))

                .add("top-plate-outside-1", new ModelCuboid()
                        .brightness(15)
                        .material(Material.BLUE_CONCRETE)
                        .size(3.5F, 0.7F, 1.1F)
                        .location(0, 10.0F, 0)
                        .rotation(0))
                .add("top-plate-outside-2", new ModelCuboid()
                        .brightness(15)
                        .material(Material.BLUE_CONCRETE)
                        .size(3.5F, 0.7F, 1.1F)
                        .location(0, 10.0F, 0)
                        .rotation(Math.PI / 4))
                .add("top-plate-outside-3", new ModelCuboid()
                        .brightness(15)
                        .material(Material.BLUE_CONCRETE)
                        .size(3.5F, 0.7F, 1.1F)
                        .location(0, 10.0F, 0)
                        .rotation(Math.PI / 2))
                .add("top-plate-outside-4", new ModelCuboid()
                        .brightness(15)
                        .material(Material.BLUE_CONCRETE)
                        .size(3.5F, 0.7F, 1.1F)
                        .location(0, 10.0F, 0)
                        .rotation(Math.PI * 3 / 4))

                .add("top-spike-pillar-1", new ModelCuboid()
                        .brightness(15)
                        .material(Material.WHITE_CONCRETE)
                        .size(0.35F, 5.0F, 0.35F)
                        .location(0.9F, 12.7F, 0.0F)
                        .rotation(0, 0, Math.PI * 1 / 12))
                .add("top-spike-pillar-2", new ModelCuboid()
                        .brightness(15)
                        .material(Material.WHITE_CONCRETE)
                        .size(0.35F, 5.0F, 0.35F)
                        .location(0.64F, 12.7F, -0.64F)
                        .rotation(0, Math.PI / 4, Math.PI * 1 / 12))
                .add("top-spike-pillar-3", new ModelCuboid()
                        .brightness(15)
                        .material(Material.WHITE_CONCRETE)
                        .size(0.35F, 5.0F, 0.35F)
                        .location(0.0F, 12.7F, -0.9F)
                        .rotation(0, Math.PI / 2, Math.PI * 1 / 12))
                .add("top-spike-pillar-4", new ModelCuboid()
                        .brightness(15)
                        .material(Material.WHITE_CONCRETE)
                        .size(0.35F, 5.0F, 0.35F)
                        .location(-0.64F, 12.7F, -0.64F)
                        .rotation(0, Math.PI * 3 / 4, Math.PI * 1 / 12))
                .add("top-spike-pillar-5", new ModelCuboid()
                        .brightness(15)
                        .material(Material.WHITE_CONCRETE)
                        .size(0.35F, 5.0F, 0.35F)
                        .location(-0.9F, 12.7F, 0.0F)
                        .rotation(0, Math.PI, Math.PI * 1 / 12))
                .add("top-spike-pillar-6", new ModelCuboid()
                        .brightness(15)
                        .material(Material.WHITE_CONCRETE)
                        .size(0.35F, 5.0F, 0.35F)
                        .location(-0.64F, 12.7F, 0.64F)
                        .rotation(0, Math.PI * 5 / 4, Math.PI * 1 / 12))
                .add("top-spike-pillar-7", new ModelCuboid()
                        .brightness(15)
                        .material(Material.WHITE_CONCRETE)
                        .size(0.35F, 5.0F, 0.35F)
                        .location(0, 12.7F, 0.9F)
                        .rotation(0, Math.PI * 3 / 2, Math.PI * 1 / 12))
                .add("top-spike-pillar-8", new ModelCuboid()
                        .brightness(15)
                        .material(Material.WHITE_CONCRETE)
                        .size(0.35F, 5.0F, 0.35F)
                        .location(0.64F, 12.7F, 0.64F)
                        .rotation(0, Math.PI * 7/ 4, Math.PI * 1 / 12));
    }
}
